apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign-service
  namespace: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: campaign-service
  template:
    metadata:
      labels:
        app: campaign-service
    spec:
      containers:
        - name: campaign-service
          image: food-delivery/campaign-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: advertisement-config
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8088
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8088
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
