apiVersion: v1
kind: Service
metadata:
  name: campaign-service
  namespace: food-delivery
spec:
  selector:
    app: campaign-service
  ports:
    - protocol: TCP
      port: 8097
      targetPort: 8097
